import Footer from "@/components/layout/footer";
import Header from "@/components/layout/header";
import "@/styles/global.scss";
import { Outfit } from "next/font/google";

const outfit = Outfit({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  style: ["normal"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Kamyoon Tech",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
